# Generated by Django 2.2.6 on 2019-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggo',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
