# Generated by Django 2.2.6 on 2019-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apap', '0002_doggo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggo',
            name='gender',
            field=models.IntegerField(default=None),
        ),
    ]
